#
# Copyright (c) 2014 ISPRAS
#
# Institute for System Programming of Russian Academy of Sciences
#
# 25 Alexander Solzhenitsyn st. Moscow 109004 Russia
#
# All rights reserved.
#
# config.rb, Apr 14, 2014 9:11:07 PM
#

#
# Description:
#
# This is the configuration file for Test Templates subsystem.
# It contains information related to package and folder structure
# and other global settings for the subsystem. 
#

# Folders and Packages 

WD               = Dir.pwd
HOME             = ENV["MICROTESK_HOME"]

JARS             = File.join(HOME, "lib/jars")
TOOLS            = File.join(HOME, "tools")

FORTRESS_JAR     = File.join(JARS, "fortress.jar")
MICROTESK_JAR    = File.join(JARS, "microtesk.jar")
MODELS_JAR       = File.join(JARS, "models.jar")

TEMPLATE         = File.join(HOME, "lib/ruby/template")

MODEL_CLASS_FRMT = "ru.ispras.microtesk.model.%s.Model"

# Debugging features 

$TO_STDOUT = true # Write results to stdout?
$TO_FILES  = true # Write results to files?

# Header for generated assembly files

HEADER_TEXT =
"; This test program was automatically generated by MicroTESK\n" +
"; Generation started: %s\n;\n" +
"; Institute for System Programming of the Russian Academy of Sciences (ISPRAS)\n" +
"; 25, Alexander Solzhenitsyn st., Moscow, 109004, Russia\n" +
"; http://forge.ispras.ru/projects/microtesk\n\n"
