	//==============================================================================
	// 
	// This test program was automatically generated by the MicroTESK tool
	// Generation started: Mon Jun 22 14:37:05 MSK 2015
	// 
	// Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	// http://forge.ispras.ru/projects/microtesk
	// 
	//==============================================================================
	
	//==============================================================================
	// Prologue
	//==============================================================================
	
	// Empty
	
	//================================== Test 0 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 1 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 2 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 3 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 4 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 5 ====================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 6 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 7 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 8 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================== Test 9 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 10 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 11 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 12 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 13 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 14 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 15 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 16 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 17 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 18 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 19 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 20 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 21 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 22 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 23 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 24 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 25 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 26 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 27 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 28 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 29 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 30 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 31 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 32 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 33 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 34 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 35 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 36 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 37 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 38 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 39 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 40 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 41 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 42 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 43 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 44 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 45 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 46 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 47 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 48 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 49 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 50 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 51 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 52 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 53 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 54 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 55 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 56 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 57 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 58 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 59 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 60 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 61 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 62 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 63 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 64 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 65 ====================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 66 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 67 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 68 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 69 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 70 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 71 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 72 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 73 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 74 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 75 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 76 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 77 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 78 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 79 ====================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 80 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 81 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 82 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 83 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 84 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 85 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 86 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 87 ====================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 88 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 89 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 90 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 91 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 92 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 93 ====================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 94 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 95 ====================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 96 ====================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 97 ====================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x2
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 98 ====================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 99 ====================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 100 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 101 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 102 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 103 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 104 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 105 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 106 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 107 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 108 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 109 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 110 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 111 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 112 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x2
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 113 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//==============================================================================
	// Epilogue
	//==============================================================================
	
	// Empty
