	//==============================================================================
	// 
	// This test program was automatically generated by the MicroTESK tool
	// Generation started: Mon Jun 22 14:37:16 MSK 2015
	// 
	// Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	// http://forge.ispras.ru/projects/microtesk
	// 
	//==============================================================================
	
	//==============================================================================
	// Prologue
	//==============================================================================
	
	// Empty
	
	//================================= Test 228 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 229 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 230 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 231 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 232 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 233 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 234 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 235 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 236 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 237 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 238 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 239 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 240 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 241 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 242 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 243 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 244 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 245 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 246 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 247 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 248 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 249 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 250 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 251 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 252 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 253 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 254 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 255 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 256 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 257 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 258 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 259 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 260 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 261 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 262 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 263 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 264 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 265 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 266 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 267 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 268 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 269 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 270 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 271 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 272 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 273 ===================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 274 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 275 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 276 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 277 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 278 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 279 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 280 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 281 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 282 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 283 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 284 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 285 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 286 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 287 ===================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 288 ===================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 289 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 290 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 291 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 292 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 293 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 294 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 295 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 296 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 297 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 298 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 299 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//==============================================================================
	// Epilogue
	//==============================================================================
	
	// Empty
