	//==============================================================================
	// 
	// This test program was automatically generated by the MicroTESK tool
	// Generation started: Mon Jun 22 14:37:10 MSK 2015
	// 
	// Institute for System Programming of the Russian Academy of Sciences (ISP RAS)
	// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
	// http://forge.ispras.ru/projects/microtesk
	// 
	//==============================================================================
	
	//==============================================================================
	// Prologue
	//==============================================================================
	
	// Empty
	
	//================================= Test 114 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 115 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 116 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 117 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 118 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 119 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 120 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 121 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 122 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 123 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 124 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 125 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 126 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 127 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	or $9, $0, $0
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 128 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 129 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 130 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 131 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 132 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 133 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 134 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 135 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 136 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 137 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 138 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 139 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 140 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 141 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 142 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 143 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	or $9, $0, $0
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 144 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 145 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 146 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 147 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 148 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 149 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 150 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 151 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 152 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 153 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 154 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 155 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 156 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 157 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 158 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 159 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 160 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 161 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 162 ===================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 163 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 164 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	or $9, $0, $0
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 165 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 166 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 167 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 168 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 169 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 170 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 171 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 172 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 173 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 174 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 175 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 176 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 177 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 178 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 179 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x1
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 180 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 181 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 182 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 183 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 184 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 185 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	or $9, $0, $0
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 186 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 187 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	addi $9, $0, 0x2
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 188 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 189 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	addi $10, $0, 0x1
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 190 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 191 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 192 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 193 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 194 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 195 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 196 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 197 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 198 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 199 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 200 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 201 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 202 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 203 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 204 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 205 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 206 ===================================
	
	// Preparation
	addi $8, $0, 0x2
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 207 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	addi $9, $0, 0x1
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 208 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 209 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x2
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 210 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 211 ===================================
	
	// Preparation
	lui $8, 0xbad
	addi $8, $8, 0xf00d
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 212 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 213 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 214 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 215 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xbad
	addi $9, $9, 0xf00d
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 216 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	lui $9, 0xffff
	addi $9, $9, 0xffff
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 217 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 218 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	addi $9, $0, 0x2
	addi $10, $0, 0x2
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 219 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	lui $9, 0xffff
	addi $9, $9, 0xffff
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 220 ===================================
	
	// Preparation
	or $8, $0, $0
	addi $9, $0, 0x2
	lui $10, 0xdead
	addi $10, $10, 0xbeef
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 221 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xffff
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 222 ===================================
	
	// Preparation
	lui $8, 0xffff
	addi $8, $8, 0xfffe
	addi $9, $0, 0x1
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 223 ===================================
	
	// Preparation
	or $8, $0, $0
	or $9, $0, $0
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 224 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xffff
	addi $10, $10, 0xfffe
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 225 ===================================
	
	// Preparation
	or $8, $0, $0
	lui $9, 0xdead
	addi $9, $9, 0xbeef
	lui $10, 0xbad
	addi $10, $10, 0xf00d
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 226 ===================================
	
	// Preparation
	lui $8, 0xdead
	addi $8, $8, 0xbeef
	lui $9, 0xffff
	addi $9, $9, 0xffff
	or $10, $0, $0
	
	// Stimulus
	add $8, $9, $10
	
	//================================= Test 227 ===================================
	
	// Preparation
	addi $8, $0, 0x1
	lui $9, 0xffff
	addi $9, $9, 0xfffe
	lui $10, 0xffff
	addi $10, $10, 0xffff
	
	// Stimulus
	add $8, $9, $10
	
	//==============================================================================
	// Epilogue
	//==============================================================================
	
	// Empty
