/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_GLISS_INCLUDE_GLISS_CATEGORY_H
#define GLISS_GLISS_INCLUDE_GLISS_CATEGORY_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define GLISS_CATEGORY_STATE
#define GLISS_CATEGORY_INIT(s)
#define GLISS_CATEGORY_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_GLISS_INCLUDE_GLISS_CATEGORY_H */
