/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
/* #include <math.h>  needed for affiche_valeur_binaire (which is not well categoryd) */

#include <gliss/api.h>
#include "config.h" /* for memory endiannesses */
#include "category.h"

#include "category_table.h"


/**
 * Return the category of a given instruction.
 * @param inst		Current instruction to execute.
 */
void gliss_category(gliss_inst_t *inst)
{
	gliss_category_table[inst->ident];
}


/* End of file gliss_category.c */
