/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_GLISS_INCLUDE_GLISS_INST_SIZE_H
#define GLISS_GLISS_INCLUDE_GLISS_INST_SIZE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define GLISS_INST_SIZE_STATE
#define GLISS_INST_SIZE_INIT(s)
#define GLISS_INST_SIZE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_GLISS_INCLUDE_GLISS_INST_SIZE_H */
