/*
 * Copyright (c) ISPRAS
 * 
 * Institute for System Programming of Russian Academy of Sciences
 * 
 * 25 Alexander Solzhenitsyn st. Moscow 109004 Russia
 * 
 * All rights reserved.
 * 
 * This file was automatically generated by MicroTEST based on the
 * information contained in the 'large_addr.nml' specification file.
 * 
 * N.B. PLEASE DO NOT MODIFY THIS FILE.
 */

package ru.ispras.microtesk.model.large_addr.op;

import java.util.Map;
import java.math.BigInteger;
import ru.ispras.microtesk.model.api.instruction.IOperation;
import ru.ispras.microtesk.model.api.instruction.Operation;
import ru.ispras.microtesk.model.api.ArgumentMode;
import ru.ispras.microtesk.model.api.type.*;
import ru.ispras.microtesk.model.api.data.*;
import ru.ispras.microtesk.model.api.memory.*;

import static ru.ispras.microtesk.model.large_addr.shared.Shared.*;

public final class instruction extends Operation {
  private static final class Info extends InfoAndRule {
    Info()
    {
        super(
           instruction.class,
           "instruction",
           true,
           new ParamDecls());
    }

    @Override
    public IOperation create(Map<String, Object> args)
    {
        return new instruction();
    }
  }

  public static final IInfo INFO = new Info();

  public instruction()
  {
  }

  @Override
  public void action()
  {
      M48.access(0x800000000000L).store(DataEngine.valueOf(Type.INT(0x40), 0xffffffffffffL));
      M64.access(new BigInteger("8000000000000000", 16)).store(DataEngine.valueOf(Type.INT(0x40), new BigInteger("ffffffffffffffff", 16)));
  }
}
