/*
 * Copyright (c) ISPRAS
 * 
 * Institute for System Programming of Russian Academy of Sciences
 * 
 * 25 Alexander Solzhenitsyn st. Moscow 109004 Russia
 * 
 * All rights reserved.
 * 
 * This file was automatically generated by MicroTEST based on the
 * information contained in the 'large_addr.nml' specification file.
 * 
 * N.B. PLEASE DO NOT MODIFY THIS FILE.
 */

package ru.ispras.microtesk.model.large_addr.op;

import java.util.Map;
import java.math.BigInteger;
import ru.ispras.microtesk.model.api.instruction.IOperation;
import ru.ispras.microtesk.model.api.instruction.Operation;
import ru.ispras.microtesk.model.api.ArgumentMode;
import ru.ispras.microtesk.model.api.type.*;
import ru.ispras.microtesk.model.api.data.*;
import ru.ispras.microtesk.model.api.memory.*;
import ru.ispras.microtesk.model.api.instruction.IAddressingMode;
import ru.ispras.microtesk.model.large_addr.mode.*;
import ru.ispras.microtesk.model.api.memory.Location;

import static ru.ispras.microtesk.model.large_addr.shared.Shared.*;

public final class sw64 extends Operation {
  private static final class Info extends InfoAndRule {
    Info()
    {
        super(
           sw64.class,
           "sw64",
           true,
           new ParamDecls()
               .declareParam("rd", ArgumentMode.IN, r64.INFO)
               .declareParam("addr", WORD64));
    }

    @Override
    public IOperation create(Map<String, Object> args)
    {
        final IAddressingMode rd = (IAddressingMode) getArgument("rd", args);
        final Location addr = (Location) getArgument("addr", args);

        return new sw64(rd, addr);
    }
  }

  public static final IInfo INFO = new Info();

  private final IAddressingMode rd;
  private final Location addr;

  public sw64(IAddressingMode rd, Location addr)
  {
      assert r64.INFO.isSupported(rd);
      assert WORD64.equals(addr.getType());

      this.rd = rd;
      this.addr = addr;
  }

  @Override
  public String syntax()
  {
      return String.format("sw64 %s, %x", rd.syntax(), addr.load().getRawData().longValue());
  }

  @Override
  public void action()
  {
      M64.access(addr.load()).store(rd.access().load());
  }
}
