/*
 * Copyright (c) 2012 ISPRAS
 * 
 * Institute for System Programming of Russian Academy of Sciences
 * 
 * 25 Alexander Solzhenitsyn st. Moscow 109004 Russia
 * 
 * All rights reserved.
 * 
 * $Id: ESenderKind.java, Jul 30, 2012 4:09:29 PM Andrei Tatarnikov Exp $
 */

package ru.ispras.microtesk.translator.antlrex.log;

/**
 * The ESenderKind enumeration signifies the subsystem responsible for raising 
 * an event to be registered in the log.
 * 
 * @author Andrei Tatarnikov
 */

public enum ESenderKind
{
    /**
     * The lexer class (generated by ANTLR). 
     */
	LEXER,

	/**
	 * The parser class (generated by ANTLR).
	 */
	PARSER,
	
	/**
	 * The syntactic analyzer built on top of the parser (MicroTESK)
	 */
	
	SYNTACTIC,

	/**
	 * The tree parser class (generated by ANTLR).
	 */
	TREEWALKER,

	/**
	 * The semantic analyzer built on top of the tree parser (MicroTESK).
	 */
	SEMANTIC,

	/**
	 * Code generation logic (MicroTESK).
	 */
	EMITTER
}
