/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include "../include/$(proc)/api.h"
#include "../include/$(proc)/id.h"
#include "../include/$(proc)/macros.h"

typedef unsigned long kind_t;

static kind_t kinds[] = {
	0$(foreach instructions),
	$(otawa_kind) /* $(IDENT) */$(end)
};


/**
 * Get the OTAWA kind of the instruction.
 * @return OTAWA kind.
 */
kind_t $(proc)_kind($(proc)_inst_t *inst) {
	return kinds[inst->ident];
}
