/*
 * Copyright (c) ISPRAS
 * 
 * Institute for System Programming of Russian Academy of Sciences
 * 
 * 25 Alexander Solzhenitsyn st. Moscow 109004 Russia
 * 
 * All rights reserved.
 * 
 * This file was automatically generated by MicroTEST based on the
 * information contained in the 'general.nml' specification file.
 * 
 * N.B. PLEASE DO NOT MODIFY THIS FILE.
 */

package ru.ispras.microtesk.model.general.op;

import java.util.Map;
import java.math.BigInteger;
import ru.ispras.microtesk.model.api.instruction.IOperation;
import ru.ispras.microtesk.model.api.instruction.Operation;
import ru.ispras.microtesk.model.api.ArgumentMode;
import ru.ispras.microtesk.model.api.type.*;
import ru.ispras.microtesk.model.api.data.*;
import ru.ispras.microtesk.model.api.memory.*;
import ru.ispras.microtesk.model.api.instruction.IOperation;

import static ru.ispras.microtesk.model.general.shared.Shared.*;

public final class instruction extends Operation {
  private static final class Info extends InfoAndRule {
    Info()
    {
        super(
           instruction.class,
           "instruction",
           true,
           new ParamDecls()
               .declareParam("x", test.INFO));
    }

    @Override
    public IOperation create(Map<String, Object> args)
    {
        final IOperation x = (IOperation) getArgument("x", args);

        return new instruction(x);
    }
  }

  public static final IInfo INFO = new Info();

  private final IOperation x;

  public instruction(IOperation x)
  {
      assert test.INFO.isSupported(x);

      this.x = x;
  }

  @Override
  public String syntax()
  {
      return x.syntax();
  }

  @Override
  public String image()
  {
      return x.image();
  }

  @Override
  public void action()
  {
      x.action();
  }
}
