/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H
#define GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define $(PROC)_DECODE_STATE
#define $(PROC)_DECODE_INIT(s)
#define $(PROC)_DECODE_DESTROY(s)

#define $(PROC)_INF_DECODE_CACHE

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H */
