/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H
#define GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define $(PROC)_DECODE_STATE
#define $(PROC)_DECODE_INIT(s)
#define $(PROC)_DECODE_DESTROY(s)

#define $(PROC)_DTRACE_CACHE
#ifndef TRACE_DEPTH
#define TRACE_DEPTH (32) /* Must be a power of two */
#endif                   /* and don't forget to update TRACE_DEPTH_PW */
/* TRACE_DEPTH is a power of two (2^N) */
/* TRACE_DEPTH_PW is N */
#ifndef TRACE_DEPTH_PW
#define TRACE_DEPTH_PW (5)
#endif


#if defined(__cplusplus)
}
#endif

#endif /* GLISS_$(PROC)_INCLUDE_$(PROC)_DECODE_H */
