/* Generated by regana ($(date)) copyright (c) 2009 IRIT - UPS */

/* implementation of functions */
int usage_unknown($(proc)_inst_t *inst, $(proc)_reg_use_t *regs) {
	return 0;
}

$(foreach instructions)
int usage_$(IDENT)($(proc)_inst_t *inst, $(proc)_reg_use_t *regs) {
	int i = 0;
$(foreach USED_REGS)
	regs[i].id = $(REG_ID);
	regs[i].index = $(REG_INDEX);
	regs[i].access = $(REG_ACCESS);
	i++;
$(end)
	return i;
}
$(end)

/* vector table */
typedef int (*usage_t)($(proc)_inst_t *inst, $(proc)_reg_use_t *regs);
static usage_t usage_table[] = {
	usage_unknown$(foreach instructions),
	usage_$(IDENT)$(end)};

/**
 * compute the register usage
 * @param inst	Analyzed instruction.
 * @param regs	Register usage array to write to.
 * @return		Number of used item in the array.
 */
int $(proc)_register_usage($(proc)_inst_t *inst, $(proc)_reg_use_t *regs) {
	
}
