/* Generated by $(version) ($(date)) */
#ifndef $(PROC)_STATE_H
#define $(PROC)_STATE_H

#include <$(proc)/api.h>
$(foreach modules)
#include "$(name).h"
$(end)

/* $(proc)_full_state_t structure */
typedef struct $(proc)_full_state_t {
	$(proc)_state_t state;
$(foreach modules)
	$(PROC)_$(NAME)_STATE
$(end)
} $(proc)_full_state_t;

#endif	/* $(PROC)_STATE_H */
